language: node_js
node_js: 4
cache:
  directories:
    - node_modules
before_install:
  - rvm install 2.2.2
install:
  - npm install
  - gem install scss_lint
script:
  - npm run lint
notifications:
  slack:
    secure: njFazX2tSawzKfn5xzNsNNchPrr8MysHs1AJwzqmFXcYQpEhdjxG0MxpUS8WJBBy0a5gbYqQNkM/YTyLY9nCFvAxrx65lCvKuR3+I7NO8qk8VfRIjZmlCSPNXyd0rw9qpoefI7icRa71HTUiw09ksrcmnG5dPDi3Sv6lm0zyOptShFGJPTYi6iKUQCFOKln5mIxx1LKjSx6/MYaIwnqKOagNE2tJTvjy9pm1AQN18Nk8GxAt29Gdd+ZiTb/cOMjmzjyA/WMtRn/Ya3dBabX9SAd/ty7mPSKrGHd/YlXric4+89Q/LCjEcAjs4H2yUSFlPV/3gzhFDZb8xCLYQ8jCUzE/mu3ndZHrdVJ96jCeok0IrncU6qA2JvEu6GPEmNfbLKsZMQZqhUh4NGBUciqymmgf/T65YHNY1RSl+X6gI+LtpXNsrVhHhbraJ5DDSd/mt+IBt6vsSx5S4BE0FpfGvAjfOUOCyLfK1YCPXlUR/ORus2XepiYMxTStbXpDkoF6HEqBh1zHHesFftN4owNhyddk27EhUOUy+jTmMgvWmkbwH/175TE9N1NkC5dBoBX5zbSxt8g3DgX6OhycCQpEJ47/Kn5aVopUMb9NJ9TLk9TzWy4r/6vNTM2ILKe+mNrtPhyj9/0cNkqUkxJStuY2Az3q3SKR7PousuEc25+PzRw=
